#==================================spring boot应用基本配置start==================================#
spring:
  application:
    name: security-test

#swagger
swagger:
  version: v0.0.9

#阿里
ali:
  satisficerCodeTemp: 1111
  handleCodeTemp: 1111
  aliAppcode: 1111

filePath:
  # 最大允许的单个文件上传大小(单位MB)
  maxFileSize: 10
  #图片存储的根路径 D:/data_spring/alarm/file/
  fileRoot: D:/data_spring/alarm/file
#  远程调用im服务器的地址
im:
  url: http://11.11.11.11:1111
#  视频转码配置
video:
  convert-config: /data_spring/t_gbpx/convert.sh

#==================================spring boot应用基本配置end==================================#

#==================================ssl设置start==================================#
#1、主配置设置ssl，sslconfig中设置http
#2、主配置设置http，sslconfig中设置ssl
#https应用的设置：1、申请证书（固定域名），2、应用内配置，3、修改服务器域名host为申请证书时的域名
#server:
#  port: 8899
#  ssl:
#    key-store-password: 0kif1y49
#    key-store: classpath:yjbj.jks
#    key-alias: alias
#    key-store-type: JKS
#==================================ssl设置end==================================#

#==================================thymeleaf start==================================#
#  thymeleaf:
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    content-type: text/html
#    #开发时关闭缓存,不然没法看到实时页面
#    cache: false
#==================================thymeleaf end==================================#
---
server:
  port: 8080
  tomcat:
    basedir: E:/test
spring:
  profiles: demo
  jpa:
    show-sql: true
    generate-ddl: false
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/security_test?characterEncoding=UTF-8
    username:  root
    password:  root
    driverClassName: com.mysql.jdbc.Driver
author:
  #主要是拦截后台管理端的路径
  ignoreUrls: /admin/**,/v1/security/loginFail,/v1/user/hello,/v1/security/loginSuccess,/v1/log/**
logging:
  level: debug

---
#测试开发时，tomcat临时运行文件路径
server:
  port: 7770
  tomcat:
    basedir: E:/test
#测试用数据库配置
spring:
  profiles: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/security_test?characterEncoding=UTF-8
    username:  root
    password:  root
    driverClassName: com.mysql.jdbc.Driver

#授权处理
author:
#不需要登录即可直接访问的url
#  /admin/login.html,/v1/security/loginFail,/v1/user/hello,/login,/v1/security/loginSuccess,/favicon.ico,/v1/security/logoutSuccess
  ignoreUrls: /**
logging:
  level: debug





